<?php

namespace BimoBundle\Repository;

/**
 * HospRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HospRepository extends \Doctrine\ORM\EntityRepository
{
}
