<?php

namespace BimoBundle\Repository;

/**
 * MedProtoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedProtoRepository extends \Doctrine\ORM\EntityRepository
{
}
