<?php

namespace BimoBundle\Repository;

/**
 * MedProtoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedProtoRepository extends \Doctrine\ORM\EntityRepository
{
    public function dosageExpressionInit($texte)
    {
    	if (preg_match("#^[0-9][-._/,;:* ]?[0-9][-._/,;:* ]?[0-9]$#", $texte))
		{
		    $texte = preg_replace('#^([0-9])[-._/,;:* ]?([0-9])[-._/,;:* ]?([0-9])$#', "matin $1 \nmidi $2 \nsoir $3", $texte);	    
		}
		return $texte;
    }

    public function dosageExpressionReset($texte)
    {
    	if (preg_match("#^matin [0-9] midi [0-9] soir [0-9]$#", $texte))
		{
		    $texte = preg_replace("#^matin ([0-9]) midi ([0-9]) soir ([0-9])$#", "matin $1 \n midi $2 \n soir $3", $texte);	    
		}
		return $texte;
    }

    public function dosageExpression($texte){
    	if (preg_match("#^[0-9][-._/,;:* ]?[0-9][-._/,;:* ]?[0-9]$#", $texte)) // 898
		{
		    $texte = preg_replace('#^([0-9])[-._/,;:* ]?([0-9])[-._/,;:* ]?([0-9])$#', "matin $1\nmidi $2\nsoir $3", $texte);	   
		    return $texte;
		}	
		elseif (preg_match("#^matin [0-9]midi [0-9]soir [0-9]$#", $texte)) // matin 6midi 8soir 7 
		{
		    $texte = preg_replace("#^matin ([0-9])midi ([0-9])soir ([0-9])$#", "matin $1\nmidi $2\nsoir $3", $texte);	
		    return $texte;    
		}
		else
			return $texte; 		
    }
}
