<?php

namespace UserBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use UserBundle\Entity\User;
use BimoBundle\Entity\Bimo;

/**
 * UserBimoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserBimoRepository extends \Doctrine\ORM\EntityRepository
{

	public function getLastUBofUser(\UserBundle\Entity\User $user) {
		//Pour chaque bimo modifi", renvois la dernière date de modification
		$query = $this
	    	->createQueryBuilder('ub')
	    	->where('ub.user = :user')->setParameter('user', $user)
	    	->orderBy('ub.bimo')	
	    ;
	    return $query
			->getQuery()
			->getResult()
		;	
	}

	public function getUB(User $user, \BimoBundle\Entity\Bimo $bimo) {
		$query = $this
	    	->createQueryBuilder('ub')
	    	->where('ub.user = :user')
	    	->andWhere('ub.bimo = :bimo')
	    	->setParameter('user', $user)
	    	->setParameter('bimo', $bimo)
	    ;
	    return $query
			->getQuery()
			->getResult()
		;  
	}

	public function getUBbyUser(\UserBundle\Entity\User $user) {
		$query = $this
	    	->createQueryBuilder('ub')
	    	->where('ub.user = :user')
	    	->setParameter('user', $user)
	    	->orderBy('ub.updatedAt','DESC')
	    	->setMaxResults(1);
	    ;
	    return $query
			->getQuery()
			->getResult()
		;  
	}

	public function getUBbyBimo(\BimoBundle\Entity\Bimo $bimo) {
		$query = $this
	    	->createQueryBuilder('ub')
	    	->where('ub.bimo = :bimo')
	    	->setParameter('bimo', $bimo)
	    	->orderBy('ub.updatedAt','DESC')
	    ;
	    return $query
			->getQuery()
			->getResult()
		;  
	}

}
