<?php

namespace UserBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserBimoRepository extends \Doctrine\ORM\EntityRepository
{
	public function getUB(User $user, \BimoBundle\Entity\Bimo $bimo) {
		$query = $this
	    	->createQueryBuilder('ub')
	    	->where('ub.user = :user')
	    	->andWhere('ub.bimo = :bimo')
	    	->setParameter('user', $user)
	    	->setParameter('bimo', $bimo)
	    ;
	    return $query
			->getQuery()
			->getResult()
		;  
	}

	public function getUBbyUser(User $user) {
		$query = $this
	    	->createQueryBuilder('ub')
	    	->where('ub.user = :user')
	    	->setParameter('user', $user)
	    ;
	    return $query
			->getQuery()
			->getResult()
		;  
	}

	public function getUBbyBimo(\BimoBundle\Entity\Bimo $bimo) {
		$query = $this
	    	->createQueryBuilder('ub')
	    	->where('ub.bimo = :bimo')
	    	->setParameter('bimo', $bimo)
	    ;
	    return $query
			->getQuery()
			->getResult()
		;  
	}

}
