<?php

namespace UserBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function getUsers($page,$nbPerPage)
  	{
	    $query = $this
	    	->createQueryBuilder('u')
	    ;

	    $query
	    // On définit l'annonce à partir de laquelle commencer la liste
	    	->setFirstResult(($page-1) * $nbPerPage)
	    // Ainsi que le nombre d'annonce à afficher sur une page
	    	->setMaxResults($nbPerPage)
	    ;

	    // Enfin, on retourne l'objet Paginator correspondant à la requête construite
	    // (n'oubliez pas le use correspondant en début de fichier)
	    return new Paginator($query, true);
	}

	public function getUserByUsername($username)
  	{
	    $query = $this
	    	->createQueryBuilder('u')
	    	->where('u.username = :username')
	    	->setParameter('username', $username)
	    ;
	    return $query
			->getQuery()
			->getOneOrNullResult();
		;  
	}	

	public function getUser($id)
  	{
	    $query = $this
	    	->createQueryBuilder('u')
	    	->where('u.id = $id')
	    ;
	    return $query;   
	}

}
